<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-mixer8_downloader-de0f0315-079b-4993-8030-3be729b8339f</UserSecretsId>
    <RootNamespace>mixer8_downloader</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dotenv.net" Version="4.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
  </ItemGroup>
</Project>
