<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Mixer8.Waveformer-2ea9a07d-3a95-4ade-93b5-d8187d1a8987</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dotenv.net" Version="4.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
  </ItemGroup>
</Project>
