// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mixer8.Api.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mixer8.Api.Infrastructure.Migrations
{
    [DbContext(typeof(Mixer8DbContext))]
    [Migration("20260716234138_AddTrackBpmAndKey")]
    partial class AddTrackBpmAndKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mixer8.Api.Domain.Album", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PlayCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AlbumId");

                    b.ToTable("Albums", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.Playlist", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<long>("PlayCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlaylistId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Playlists", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.PlaylistCollaborator", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlaylistId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PlaylistCollaborators", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.PlaylistTrack", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddedById")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistId", "TrackId");

                    b.HasIndex("AddedById");

                    b.HasIndex("TrackId");

                    b.ToTable("PlaylistTracks", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.SavedPlaylist", b =>
                {
                    b.Property<Guid>("SavedPlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SavedPlaylistId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedPlaylists", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.Stem", b =>
                {
                    b.Property<Guid>("StemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("StemId");

                    b.HasIndex("TrackId");

                    b.ToTable("Stems", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.StemWaveform", b =>
                {
                    b.Property<Guid>("StemId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<int>>("Points")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("StemId");

                    b.ToTable("StemWaveforms", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.SystemEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId");

                    b.ToTable("SystemEvents", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.Track", b =>
                {
                    b.Property<Guid>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Bpm")
                        .HasColumnType("integer");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeletionPending")
                        .HasColumnType("boolean");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("text");

                    b.Property<int>("DiscNumber")
                        .HasColumnType("integer");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<long>("PlayCount")
                        .HasColumnType("bigint");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TrackTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("WeekPlayCount")
                        .HasColumnType("bigint");

                    b.HasKey("TrackId");

                    b.HasIndex("AlbumId");

                    b.HasIndex("WeekPlayCount");

                    b.ToTable("Tracks", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.TrackPlay", b =>
                {
                    b.Property<Guid>("TrackPlayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("TrackPlayId");

                    b.HasIndex("PlayedAt");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackPlays", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.UserProfile", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastLoginIp")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserRoleId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.Playlist", b =>
                {
                    b.HasOne("Mixer8.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixer8.Api.Domain.PlaylistCollaborator", b =>
                {
                    b.HasOne("Mixer8.Api.Domain.Playlist", "Playlist")
                        .WithMany("PlaylistCollaborators")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mixer8.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mixer8.Api.Domain.PlaylistTrack", b =>
                {
                    b.HasOne("Mixer8.Api.Domain.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mixer8.Api.Domain.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mixer8.Api.Domain.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Mixer8.Api.Domain.SavedPlaylist", b =>
                {
                    b.HasOne("Mixer8.Api.Domain.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mixer8.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixer8.Api.Domain.Stem", b =>
                {
                    b.HasOne("Mixer8.Api.Domain.Track", null)
                        .WithMany("Stems")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixer8.Api.Domain.StemWaveform", b =>
                {
                    b.HasOne("Mixer8.Api.Domain.Stem", null)
                        .WithOne("Waveform")
                        .HasForeignKey("Mixer8.Api.Domain.StemWaveform", "StemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixer8.Api.Domain.SystemEvent", b =>
                {
                    b.HasOne("Mixer8.Api.Domain.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mixer8.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Mixer8.Api.Domain.Track", b =>
                {
                    b.HasOne("Mixer8.Api.Domain.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Mixer8.Api.Domain.TrackPlay", b =>
                {
                    b.HasOne("Mixer8.Api.Domain.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Mixer8.Api.Domain.UserProfile", b =>
                {
                    b.HasOne("Mixer8.Api.Domain.User", null)
                        .WithOne("UserProfile")
                        .HasForeignKey("Mixer8.Api.Domain.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Mixer8.Api.Domain.UserIpLog", "AccessedIps", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("AccessCount");

                            b1.Property<DateTime>("FirstSeenAt");

                            b1.Property<string>("Ip")
                                .IsRequired();

                            b1.Property<DateTime>("LastSeenAt");

                            b1.HasKey("UserProfileId", "__synthesizedOrdinal");

                            b1.ToTable("UserProfiles");

                            b1
                                .ToJson("AccessedIps")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("Mixer8.Api.Domain.UserProfilePreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfiles");

                            b1
                                .ToJson("Preferences")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");

                            b1.OwnsOne("Mixer8.Api.Domain.NotificationPreferences", "Notifications", b2 =>
                                {
                                    b2.Property<Guid>("UserProfilePreferencesUserProfileId");

                                    b2.Property<bool>("EmailComments");

                                    b2.Property<bool>("EmailMarketing");

                                    b2.Property<bool>("EmailOrders");

                                    b2.Property<bool>("PushComments");

                                    b2.Property<bool>("PushOrders");

                                    b2.HasKey("UserProfilePreferencesUserProfileId");

                                    b2.ToTable("UserProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("UserProfilePreferencesUserProfileId");
                                });

                            b1.Navigation("Notifications")
                                .IsRequired();
                        });

                    b.Navigation("AccessedIps");

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("Mixer8.Api.Domain.UserRole", b =>
                {
                    b.HasOne("Mixer8.Api.Domain.User", null)
                        .WithOne("UserRole")
                        .HasForeignKey("Mixer8.Api.Domain.UserRole", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixer8.Api.Domain.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Mixer8.Api.Domain.Playlist", b =>
                {
                    b.Navigation("PlaylistCollaborators");

                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("Mixer8.Api.Domain.Stem", b =>
                {
                    b.Navigation("Waveform");
                });

            modelBuilder.Entity("Mixer8.Api.Domain.Track", b =>
                {
                    b.Navigation("Stems");
                });

            modelBuilder.Entity("Mixer8.Api.Domain.User", b =>
                {
                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("UserRole")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
